/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AfterSalesRole1;

import Business.Organization.AfterSalesOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Game;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ke
 */
public class GameFeedBackDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AfterSaleJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private Game concert;
    
    
    
    public GameFeedBackDetailJPanel(JPanel userProcessContainer, 
            UserAccount userAccount, 
            Game concert) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.concert =concert;
        overallProgressBar.setValue((int) concert.getOverall());
        overallProgressBar.setStringPainted(true);
        facilityProgressBar.setValue((int)concert.getFacility());
        facilityProgressBar.setStringPainted(true);
        securityBar.setValue((int) concert.getSecurity());
        securityBar.setStringPainted(true);
        serviceBar.setValue((int)concert.getService());
        serviceBar.setStringPainted(true);
        manageBar.setValue((int)concert.getManage());
        manageBar.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon(getClass().getResource("/ui/2.jpg"));
                g.drawImage(img.getImage(),0,0,1100,700,null);
            }};
            viewBtn = new javax.swing.JButton();
            backBtn = new javax.swing.JButton();
            jLabel7 = new javax.swing.JLabel();
            manageBar = new javax.swing.JProgressBar();
            jLabel5 = new javax.swing.JLabel();
            securityBar = new javax.swing.JProgressBar();
            jLabel6 = new javax.swing.JLabel();
            serviceBar = new javax.swing.JProgressBar();
            jLabel4 = new javax.swing.JLabel();
            overallProgressBar = new javax.swing.JProgressBar();
            jLabel3 = new javax.swing.JLabel();
            facilityProgressBar = new javax.swing.JProgressBar();
            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setLayout(null);

            jPanel1.setLayout(null);

            viewBtn.setBackground(new java.awt.Color(255, 255, 255));
            viewBtn.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
            viewBtn.setText("View All Comments");
            viewBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    viewBtnActionPerformed(evt);
                }
            });
            jPanel1.add(viewBtn);
            viewBtn.setBounds(291, 398, 187, 29);

            backBtn.setBackground(new java.awt.Color(255, 255, 255));
            backBtn.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
            backBtn.setText("Back");
            backBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    backBtnActionPerformed(evt);
                }
            });
            jPanel1.add(backBtn);
            backBtn.setBounds(43, 64, 77, 29);

            jLabel7.setText("Management Satification:");
            jPanel1.add(jLabel7);
            jLabel7.setBounds(98, 328, 159, 16);

            manageBar.setOpaque(true);
            manageBar.setStringPainted(true);
            jPanel1.add(manageBar);
            manageBar.setBounds(338, 328, 154, 20);

            jLabel5.setText("Security Satisfication:");
            jPanel1.add(jLabel5);
            jLabel5.setBounds(121, 254, 136, 23);

            securityBar.setOpaque(true);
            securityBar.setStringPainted(true);
            jPanel1.add(securityBar);
            securityBar.setBounds(338, 254, 154, 20);

            jLabel6.setText("Staff Service Satisfication:");
            jPanel1.add(jLabel6);
            jLabel6.setBounds(94, 283, 163, 27);

            serviceBar.setOpaque(true);
            serviceBar.setStringPainted(true);
            jPanel1.add(serviceBar);
            serviceBar.setBounds(338, 283, 154, 20);

            jLabel4.setText("Overall Score:");
            jPanel1.add(jLabel4);
            jLabel4.setBounds(171, 184, 86, 16);

            overallProgressBar.setOpaque(true);
            overallProgressBar.setStringPainted(true);
            jPanel1.add(overallProgressBar);
            overallProgressBar.setBounds(338, 184, 154, 20);

            jLabel3.setText("Facility Satisfication:");
            jPanel1.add(jLabel3);
            jLabel3.setBounds(126, 216, 131, 16);

            facilityProgressBar.setOpaque(true);
            facilityProgressBar.setStringPainted(true);
            jPanel1.add(facilityProgressBar);
            facilityProgressBar.setBounds(338, 216, 154, 20);

            jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
            jLabel2.setText("FeedBack Detail");
            jPanel1.add(jLabel2);
            jLabel2.setBounds(302, 71, 148, 22);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/kjTczgrLk4EDPmASJEnfZB.jpeg"))); // NOI18N
            jPanel1.add(jLabel1);
            jLabel1.setBounds(-200, -30, 1030, 650);

            add(jPanel1);
            jPanel1.setBounds(6, 14, 0, 0);
        }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AfterSaleJPanel asjp = (AfterSaleJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewAllCommentsJPanel manageEnterpriseJPanel=new ViewAllCommentsJPanel(userProcessContainer, userAccount, concert);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JProgressBar facilityProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar manageBar;
    private javax.swing.JProgressBar overallProgressBar;
    private javax.swing.JProgressBar securityBar;
    private javax.swing.JProgressBar serviceBar;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
