/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AfterSalesRole1;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AfterSalesOrganization;
import Business.Organization.WorldCupFansOrganization;
import Business.Organization.Organization;
import Business.Organization.BarAssignOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Game;
import Business.WorkQueue.Bar;
import Business.WorkQueue.Status;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkSend;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PrinterException;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author MingCheng
 */
public class AfterSaleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerRateJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AfterSalesOrganization afterSalesOrganization;
    private BarAssignOrganization stadiumAssignOrganization;
    
    private Enterprise enterprise;
    private EcoSystem business;
    private Bar newStadium;
    
    
    
    public AfterSaleJPanel(JPanel userProcessContainer, 
            UserAccount userAccount, 
            AfterSalesOrganization afterSalesOrganization, 
            Enterprise enterprise, 
            EcoSystem business){
        initComponents();
        
        for(Network network : business.getNetworkList()){
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof BarAssignOrganization){
                        this.stadiumAssignOrganization = (BarAssignOrganization) o;
                    }
                }
            }      
        }

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.afterSalesOrganization = afterSalesOrganization; 
        this.enterprise = enterprise;
        this.business = business;
        System.out.println("populate");
        populateTable();
        this.setSize(850, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateTable(){
       System.out.println("populate");
        Status s = Status.Complete;
        
        DefaultTableModel model = (DefaultTableModel) tblOrderInfo.getModel();
        model.setRowCount(0);
        //get info from workSend
        for (WorkRequest wr : stadiumAssignOrganization.getWorkQueue().getWorkRequestList()) {
            if(wr instanceof WorkSend){
                WorkSend ws = (WorkSend) wr;
                
                System.out.println(ws);
                Object[] row = new Object[6];
                row[0] = ws.getConcert();
                row[1] = ws.getConcert().getCity();
                
                row[2] = ws.getConcert().getConcertTime();
                row[3] = ws.getStadium().getStadiumName();
                row[4] = ws.getConcert().getOverall();
                row[5] = ws.getConcert().getComments().size();
                model.addRow(row);
            }          
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon(getClass().getResource("/ui/2.jpg"));
                g.drawImage(img.getImage(),0,0,1100,700,null);
            }};
            viewBtn = new javax.swing.JButton();
            jScrollPane3 = new javax.swing.JScrollPane();
            tblOrderInfo = new javax.swing.JTable();
            jLabel4 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            setLayout(null);

            jPanel1.setLayout(null);

            viewBtn.setBackground(new java.awt.Color(255, 255, 255));
            viewBtn.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
            viewBtn.setText("View Detail");
            viewBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    viewBtnActionPerformed(evt);
                }
            });
            jPanel1.add(viewBtn);
            viewBtn.setBounds(845, 452, 119, 29);

            tblOrderInfo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
            tblOrderInfo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Game Name", "City", "Time", "Bar", "Overall Score", "Comments Number"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, true
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane3.setViewportView(tblOrderInfo);

            jPanel1.add(jScrollPane3);
            jScrollPane3.setBounds(50, 170, 884, 268);

            jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Game Feedback");
            jPanel1.add(jLabel4);
            jLabel4.setBounds(60, 40, 146, 52);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/kjTczgrLk4EDPmASJEnfZB.jpeg"))); // NOI18N
            jPanel1.add(jLabel1);
            jLabel1.setBounds(-210, -20, 1200, 750);

            add(jPanel1);
            jPanel1.setBounds(-10, 0, 1150, 730);
        }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selected = tblOrderInfo.getSelectedRow();
        if(selected>=0){
            Game c = (Game) tblOrderInfo.getValueAt(selected, 0);
            GameFeedBackDetailJPanel manageEnterpriseJPanel=new GameFeedBackDetailJPanel(userProcessContainer, userAccount, c);
            userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblOrderInfo;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
