/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.BarAssignRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.WorldCupFansOrganization;
import Business.Organization.BarAssignOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Game;
import Business.WorkQueue.Bar;
import Business.WorkQueue.BarDirectory;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class BarAssignWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BarAssignWorkJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private BarAssignOrganization stadiumAssignOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private WorldCupFansOrganization  concertOrganization ;
    
    public BarAssignWorkJPanel(
            JPanel userProcessContainer, 
            UserAccount userAccount, 
            BarAssignOrganization stadiumAssignOrganization, 
            Enterprise enterprise, 
            EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.stadiumAssignOrganization = stadiumAssignOrganization;
        this.business = business;
        this.enterprise = enterprise;

        this.setSize(850, 800);
        this.concertOrganization = new WorldCupFansOrganization();
        for(Network network : business.getNetworkList()){
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof WorldCupFansOrganization){
                        this.concertOrganization = (WorldCupFansOrganization) o;
                    }
                }
            }      
        }

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon(getClass().getResource("/ui/3.jpg"));
                g.drawImage(img.getImage(),0,0,1100,700,null);
            }};
            btnManageConcert1 = new javax.swing.JButton();
            btnManageStadium = new javax.swing.JButton();
            lblDevider = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();

            jPanel1.setLayout(null);

            btnManageConcert1.setBackground(new java.awt.Color(255, 255, 255));
            btnManageConcert1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
            btnManageConcert1.setText("Manage Game Order");
            btnManageConcert1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnManageConcert1ActionPerformed(evt);
                }
            });
            jPanel1.add(btnManageConcert1);
            btnManageConcert1.setBounds(259, 319, 240, 32);

            btnManageStadium.setBackground(new java.awt.Color(255, 255, 255));
            btnManageStadium.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
            btnManageStadium.setText("Manage Bar");
            btnManageStadium.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnManageStadiumActionPerformed(evt);
                }
            });
            jPanel1.add(btnManageStadium);
            btnManageStadium.setBounds(259, 187, 240, 32);

            lblDevider.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
            lblDevider.setForeground(new java.awt.Color(255, 255, 255));
            lblDevider.setText("Bar Assign Work Area");
            jPanel1.add(lblDevider);
            lblDevider.setBounds(227, 60, 310, 30);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/newGame6.jpeg"))); // NOI18N
            jLabel1.setText("jLabel1");
            jPanel1.add(jLabel1);
            jLabel1.setBounds(10, 0, 900, 760);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents

    private void btnManageStadiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStadiumActionPerformed
        // TODO add your handling code here:
        ManageBarJPanel msjp = new ManageBarJPanel(
                userProcessContainer,
                userAccount,
                stadiumAssignOrganization,
                concertOrganization, 
                enterprise,
                business);
        userProcessContainer.add("ManageStadiumJPanel", msjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStadiumActionPerformed

    private void btnManageConcert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageConcert1ActionPerformed
        // TODO add your handling code here:
        ManageGameOrderJPanel mcojp = new ManageGameOrderJPanel(
                userProcessContainer,
                userAccount,
                stadiumAssignOrganization,
                concertOrganization, 
                enterprise,
                business);
        userProcessContainer.add("ManageConcertOrderJPanel", mcojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageConcert1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageConcert1;
    private javax.swing.JButton btnManageStadium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDevider;
    // End of variables declaration//GEN-END:variables
}
