/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Audience;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.Game;
import Business.WorkQueue.FeedBack;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Component;

/**
 *
 * @author 
 */
public class WriteFeedBackJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form WriteFeedBackJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Game concert;
    private int fScore;
    private int mScore;
    private int sScore;
    private int scScore;
    public WriteFeedBackJPanel1(JPanel userProcessContainer,
            UserAccount userAccount, 
            Game concert) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.concert = concert;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon(getClass().getResource("/ui/c.png"));
                g.drawImage(img.getImage(),0,0,1100,700,null);
            }
        };
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        backJButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        f1 = new javax.swing.JRadioButton();
        f2 = new javax.swing.JRadioButton();
        f3 = new javax.swing.JRadioButton();
        f4 = new javax.swing.JRadioButton();
        f5 = new javax.swing.JRadioButton();
        m1 = new javax.swing.JRadioButton();
        m2 = new javax.swing.JRadioButton();
        m3 = new javax.swing.JRadioButton();
        m4 = new javax.swing.JRadioButton();
        m5 = new javax.swing.JRadioButton();
        m2_1 = new javax.swing.JRadioButton();
        m2_2 = new javax.swing.JRadioButton();
        m2_3 = new javax.swing.JRadioButton();
        m2_4 = new javax.swing.JRadioButton();
        m2_5 = new javax.swing.JRadioButton();
        f2_1 = new javax.swing.JRadioButton();
        f2_2 = new javax.swing.JRadioButton();
        f2_3 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        s1 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        s3 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        sc1 = new javax.swing.JRadioButton();
        sc2 = new javax.swing.JRadioButton();
        sc3 = new javax.swing.JRadioButton();

        jLabel7.setText("jLabel7");

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel12.setText("How long does it take to get service?");

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel11.setText("How do you rate your everall experience?");

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel13.setText("Write down you valuable comment to help us make it better:");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FINAL RESULT");

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel14.setText("How often do you attend our event?");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel16.setText("What do you think of the cheering events? ");

        f1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f1.setText("Excellent");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        f2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f2.setText("Very Good");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f3.setText("Good");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        f4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f4.setText("Fair");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        f5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f5.setText("Poor");
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        m1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m1.setText("0 to 10 minutes");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        m2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2.setText("10 to 20 minutes");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        m3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m3.setText("20 to 30 minutes");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        m4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m4.setText("30 to 40 minutes");
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        m5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m5.setText("More than 40 minutes");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        m2_1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2_1.setText("Always");
        m2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_1ActionPerformed(evt);
            }
        });

        m2_2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2_2.setText("Usually");
        m2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_2ActionPerformed(evt);
            }
        });

        m2_3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2_3.setText("Sometimes");
        m2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_3ActionPerformed(evt);
            }
        });

        m2_4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2_4.setText("Rarely");
        m2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_4ActionPerformed(evt);
            }
        });

        m2_5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        m2_5.setText("Never");
        m2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2_5ActionPerformed(evt);
            }
        });

        f2_1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f2_1.setText("Extremely useful");
        f2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2_1ActionPerformed(evt);
            }
        });

        f2_2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f2_2.setText("Somewhat useful");
        f2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2_2ActionPerformed(evt);
            }
        });

        f2_3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        f2_3.setText("Not at all useful");
        f2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2_3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel18.setText("Did the staff engage you in a friendly manner throughtout the event?");

        s1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s1.setText("Very Friendly");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s2.setText("Maybe");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s3.setText("Not at all ");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel19.setText("How often are you pushed or hurt during the event?");

        sc1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sc1.setText("Very Often");
        sc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc1ActionPerformed(evt);
            }
        });

        sc2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sc2.setText("Sometimes");
        sc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc2ActionPerformed(evt);
            }
        });

        sc3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sc3.setText("Not at all ");
        sc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m2_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m2_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m2_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m2_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m2_5))
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(f1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f5))
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(f2_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f2_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f2_3))
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(s1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s3))
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sc3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m5))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addComponent(jLabel3)
                    .addComponent(backJButton))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backJButton)
                .addGap(110, 110, 110)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1)
                    .addComponent(f2)
                    .addComponent(f3)
                    .addComponent(f4)
                    .addComponent(f5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m1)
                    .addComponent(m2)
                    .addComponent(m3)
                    .addComponent(m4)
                    .addComponent(m5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m2_1)
                    .addComponent(m2_2)
                    .addComponent(m2_3)
                    .addComponent(m2_4)
                    .addComponent(m2_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2_1)
                    .addComponent(f2_2)
                    .addComponent(f2_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1)
                    .addComponent(s2)
                    .addComponent(s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sc1)
                    .addComponent(sc2)
                    .addComponent(sc3))
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(611, 611, 611)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc3ActionPerformed
        // TODO add your handling code here:
        sc2.setEnabled(false);
        sc1.setEnabled(false);
        this.scScore = 30;
    }//GEN-LAST:event_sc3ActionPerformed

    private void sc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc2ActionPerformed
        // TODO add your handling code here:
        sc1.setEnabled(false);
        sc3.setEnabled(false);
        this.scScore = 60;
    }//GEN-LAST:event_sc2ActionPerformed

    private void sc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc1ActionPerformed
        // TODO add your handling code here:
        sc2.setEnabled(false);
        sc3.setEnabled(false);
        this.scScore = 100;
    }//GEN-LAST:event_sc1ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
        s2.setEnabled(false);
        s1.setEnabled(false);
        this.sScore = 30;
    }//GEN-LAST:event_s3ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        s1.setEnabled(false);
        s3.setEnabled(false);
        this.sScore = 60;
    }//GEN-LAST:event_s2ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        s2.setEnabled(false);
        s3.setEnabled(false);
        this.sScore = 100;
    }//GEN-LAST:event_s1ActionPerformed

    private void f2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2_3ActionPerformed
        // TODO add your handling code here:
        f2_2.setEnabled(false);
        f2_1.setEnabled(false);
        this.fScore = (int)(30+this.fScore)/2;
    }//GEN-LAST:event_f2_3ActionPerformed

    private void f2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2_2ActionPerformed
        // TODO add your handling code here:
        f2_1.setEnabled(false);
        f2_3.setEnabled(false);
        this.fScore = (int)(60+this.fScore)/2;
    }//GEN-LAST:event_f2_2ActionPerformed

    private void f2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2_1ActionPerformed
        // TODO add your handling code here:
        f2_2.setEnabled(false);
        f2_3.setEnabled(false);
        this.fScore = (int)(100+this.fScore)/2;
    }//GEN-LAST:event_f2_1ActionPerformed

    private void m2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_5ActionPerformed
        // TODO add your handling code here:
        m2_2.setEnabled(false);
        m2_3.setEnabled(false);
        m2_4.setEnabled(false);
        m2_1.setEnabled(false);
        this.mScore = (int)(0+this.mScore)/2;
    }//GEN-LAST:event_m2_5ActionPerformed

    private void m2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_4ActionPerformed
        // TODO add your handling code here:
        m2_2.setEnabled(false);
        m2_3.setEnabled(false);
        m2_1.setEnabled(false);
        m2_5.setEnabled(false);
        this.mScore = (int)(25+this.mScore)/2;
    }//GEN-LAST:event_m2_4ActionPerformed

    private void m2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_3ActionPerformed
        // TODO add your handling code here:
        m2_2.setEnabled(false);
        m2_1.setEnabled(false);
        m2_4.setEnabled(false);
        m2_5.setEnabled(false);
        this.mScore = (int)(50+this.mScore)/2;
    }//GEN-LAST:event_m2_3ActionPerformed

    private void m2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_2ActionPerformed
        // TODO add your handling code here:
        m2_1.setEnabled(false);
        m2_3.setEnabled(false);
        m2_4.setEnabled(false);
        m2_5.setEnabled(false);
        this.mScore = (int)(75+this.mScore)/2;
    }//GEN-LAST:event_m2_2ActionPerformed

    private void m2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2_1ActionPerformed
        // TODO add your handling code here:
        m2_2.setEnabled(false);
        m2_3.setEnabled(false);
        m2_4.setEnabled(false);
        m2_5.setEnabled(false);
        this.mScore = (int)(100+this.mScore)/2;
    }//GEN-LAST:event_m2_1ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
        m2.setEnabled(false);
        m3.setEnabled(false);
        m4.setEnabled(false);
        m1.setEnabled(false);
        this.mScore = 0;
    }//GEN-LAST:event_m5ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
        m2.setEnabled(false);
        m3.setEnabled(false);
        m1.setEnabled(false);
        m5.setEnabled(false);
        this.mScore = 25;
    }//GEN-LAST:event_m4ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        m2.setEnabled(false);
        m1.setEnabled(false);
        m4.setEnabled(false);
        m5.setEnabled(false);
        this.mScore = 50;
    }//GEN-LAST:event_m3ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
        m1.setEnabled(false);
        m3.setEnabled(false);
        m4.setEnabled(false);
        m5.setEnabled(false);
        this.mScore = 75;
    }//GEN-LAST:event_m2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        m2.setEnabled(false);
        m3.setEnabled(false);
        m4.setEnabled(false);
        m5.setEnabled(false);
        this.mScore = 100;
    }//GEN-LAST:event_m1ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
        f2.setEnabled(false);
        f3.setEnabled(false);
        f4.setEnabled(false);
        f1.setEnabled(false);
        this.fScore = 0;
    }//GEN-LAST:event_f5ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
        f2.setEnabled(false);
        f3.setEnabled(false);
        f1.setEnabled(false);
        f5.setEnabled(false);
        this.fScore = 25;
    }//GEN-LAST:event_f4ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
        f1.setEnabled(false);
        f2.setEnabled(false);
        f4.setEnabled(false);
        f5.setEnabled(false);
        this.fScore = 50;
    }//GEN-LAST:event_f3ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
        f1.setEnabled(false);
        f3.setEnabled(false);
        f4.setEnabled(false);
        f5.setEnabled(false);
        this.fScore = 75;
    }//GEN-LAST:event_f2ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
        f2.setEnabled(false);
        f3.setEnabled(false);
        f4.setEnabled(false);
        f5.setEnabled(false);
        this.fScore = 100;
    }//GEN-LAST:event_f1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FeedBack feedback = new FeedBack();
        int overall = (int)(this.fScore+this.mScore+this.sScore+this.scScore)/4;
        feedback.setSocreFacility(this.fScore);
        feedback.setScoreManage(this.mScore);
        feedback.setScoreSecurity(this.scScore);
        feedback.setComment(txtComment.getText());
        feedback.setScoreService(this.sScore);
        feedback.setOverallSocre(overall);
        concert.addComments(feedback);
        JOptionPane.showMessageDialog(this, "Comment Successfully!", "Warning", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TicketOrderJPanel tojp = (TicketOrderJPanel) component;
        tojp.populateOrderJTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton f1;
    private javax.swing.JRadioButton f2;
    private javax.swing.JRadioButton f2_1;
    private javax.swing.JRadioButton f2_2;
    private javax.swing.JRadioButton f2_3;
    private javax.swing.JRadioButton f3;
    private javax.swing.JRadioButton f4;
    private javax.swing.JRadioButton f5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JRadioButton m2_1;
    private javax.swing.JRadioButton m2_2;
    private javax.swing.JRadioButton m2_3;
    private javax.swing.JRadioButton m2_4;
    private javax.swing.JRadioButton m2_5;
    private javax.swing.JRadioButton m3;
    private javax.swing.JRadioButton m4;
    private javax.swing.JRadioButton m5;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JRadioButton sc1;
    private javax.swing.JRadioButton sc2;
    private javax.swing.JRadioButton sc3;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
